### ISSUE TITLE
Error reading PDB file

### ISSUE THREAD

**Issue by sbliven** [continuous-symmetry/proteincsm#2]
I get the following error when running proteincsm (version 0.3.0 from https://repo.fury.io/theresearchsoftwarecompany):

```
$csm --babel-bond c2  /app/1dxg.pdb /app/1dxg.out
Protein-CSM version 0.3.0
225 groups of length 2
18 groups of length 4
Chain A of length 261
Chain B of length 261
1 equivalence classes of chains
Group of length 2: A B
==============================
*** Open Babel Error  in ReadFile
  Cannot read from 1dxg.pdb
Traceback (most recent call last):
  File "/usr/local/bin/csm", line 11, in <module>
    sys.exit(run_no_return())
  File "/usr/local/lib/python3.6/site-packages/csm/main/csm_run.py", line 49, in run_no_return
    run(args)
  File "/usr/local/lib/python3.6/site-packages/csm/main/csm_run.py", line 44, in run
    fw=FileWriter(result, format=dictionary_args['molecule'].metadata.format, **dictionary_args)
  File "/usr/local/lib/python3.6/site-packages/csm/input_output/writers.py", line 302, in __init__
    super().__init__(result, op_name, format, print_local)
  File "/usr/local/lib/python3.6/site-packages/csm/input_output/writers.py", line 149, in __init__
    self.result_string = self.get_result_string()
  File "/usr/local/lib/python3.6/site-packages/csm/input_output/writers.py", line 156, in get_result_string
    self._write_results(result_io)
  File "/usr/local/lib/python3.6/site-packages/csm/input_output/writers.py", line 184, in _write_results
    self.write_mol(f)
  File "/usr/local/lib/python3.6/site-packages/csm/input_output/writers.py", line 205, in write_mol
    molwriter.write(f, self.result, self.op_name, self.format)
  File "/usr/local/lib/python3.6/site-packages/csm/input_output/writers.py", line 58, in write
    self.print_output_ob(f, result, format, op_name)
  File "/usr/local/lib/python3.6/site-packages/csm/input_output/writers.py", line 76, in print_output_ob
    result.molecule.metadata.babel_bond)[0]
  File "/usr/local/lib/python3.6/site-packages/csm/molecule/molecule.py", line 1023, in _obm_from_file
    raise ValueError("Error reading file " + filename + " using OpenBabel, with format:", format)
ValueError: ('Error reading file 1dxg.pdb using OpenBabel, with format:', 'pdb')
```

I'm using openbabel 2.4.1 as suggested, but this could caused by a regression of https://sourceforge.net/p/openbabel/bugs/323/. It looks like ReadFile always returns true on my system. The fix is pretty easy: loop until the molecule read has zero atoms, rather than relying on the function return value.

Tested with a docker container running debian on a Mac 10.12 host.

**Comment by sbliven** [comment]
Commit db07eff probably fixes this, but I can't test it due to #1.
