### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by sbliven** [continuous-symmetry/proteincsm#3]
It is great that a Dockerfile is now included in the repository. However, building the project now fails:

```
$ docker build github.com/continuous-symmetry/proteincsm
Sending build context to Docker daemon  5.901MB
Step 1/5 : FROM teamcsm/openbabel:py3.5-openbabel2.4.1
 ---> b8fa44c86c61
Step 2/5 : LABEL by="The Research Software Company"
 ---> Using cache
 ---> 9f224cb13265
Step 3/5 : LABEL website="https://www.chelem.co.il"
 ---> Using cache
 ---> 2e4b796f6496
Step 4/5 : RUN pip install numpy
 ---> Using cache
 ---> 4938d8157224
Step 5/5 : RUN pip install proteincsm==1.0.0
 ---> Running in 08115213f1fc
Collecting proteincsm==1.0.0
  Downloading https://files.pythonhosted.org/packages/22/36/3f03665acd5279408b81ce99ec265a547590912fc3a52d144420af43df89/proteincsm-1.0.0.tar.gz (986kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-54a6auly/proteincsm/setup.py", line 14, in <module>
        with open(os.path.join(os.path.dirname(__file__), '..', 'README.md')) as readme:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-54a6auly/proteincsm/../README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-54a6auly/proteincsm/
You are using pip version 18.0, however version 19.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip install proteincsm==1.0.0' returned a non-zero code: 1
```

**Comment by zmbq** [comment]
Oh dear. We forgot to update the Dockerfile after updating proteincsm to 1.0.1. It should work now.

**Comment by sbliven** [comment]
I tested the change and it works great!

```
docker build -t proteincsm .
docker run -it --rm proteincsm proteincsm --help
```

You might consider adding an ENTRYPOINT so that the default command isn't a python shell.

**Comment by sbliven** [comment]
Here's some more tips for using the docker container. They're not really part of this issue, but maybe if I leave them here they will become googlable.

pdb_prep can be added to the same container easily:

```
docker run -it --name proteincsm proteincsm \
    bash -c 'pip install numpy && pip install proteincsm pdb_prep'
docker commit proteincsm proteincsm
docker run -it --rm proteincsm pdb_prep --help
```

To use the docker you have to mount the input files. I use the following workflow:

```
# Clean the input (no filters)
docker run -it --rm -v $PWD:/work proteincsm \
    pdb_prep xray --max-resolution 100  --limit-r-free-grade E \
    --verbose --output-dir /work/out --pdb-file /work/XXXX.pdb
# Compute CSM
docker run -it --rm -v $PWD:/work proteincsm \
    proteincsm c2 /work/XXXX.clean.pdb /work/XXXX.out
```
